version: "2.1"

services:
  dockovpn:
    image: alekslitvinenk/openvpn:v1.11.1
    container_name: dockovpn
    cap_add:
      - NET_ADMIN
    ports:
      - 1194:1194/udp
      - 8425:8080/tcp
    # sysctls:
    #   - net.ipv4.conf.all.src_valid_mark=1
    #   - net.ipv4.ip_forward=1
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wireguard.rule=Host(`$HOST_ADDR`)"
      - "traefik.http.routers.wireguard.entrypoints=websecure"
      - "traefik.http.routers.wireguard.tls.certresolver=letsencrypt"

networks:
  default:
    external: true
    name: traefik-proxy
    
