services:
  app:
    image: traefik/whoami:latest
    restart: unless-stopped
    labels:
        - "bunkerweb.SERVER_NAME=$HOST"
        - "bunkerweb.USE_REVERSE_PROXY=yes"
        - "bunkerweb.REVERSE_PROXY_URL=/"
        - "bunkerweb.REVERSE_PROXY_HOST=http://app:80"
        - "bunkerweb.USE_AUTH_BASIC=yes"
        - "bunkerweb.AUTH_BASIC_USER=$AUTH_BASIC_USER"
        - "bunkerweb.AUTH_BASIC_PASSWORD=$AUTH_BASIC_PASSWORD"

networks:
  default:
    external: true
    name: bw-services
