version: "3"
services:
  whoami:
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`cloud.johncloud.fr`)"

networks:
  default:
    external: true
    name: traefik-proxy
