# https://blog.filador.fr/je-supervise-mon-traefik-avec-prometheus-et-grafana/
# https://github.com/loganmarchione/homelab-svg-assets/blob/main/ICONS.md
# https://joeeey.com/blog/selfhosting-sso-with-traefik-keycloak-part-1/#setting-up-keycloak
# https://goauthentik.io/docs/providers/proxy/server_traefik

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - 80:80
      - 443:443
      - 25:25
      - 465:465
      - 993:993
      - 587:587
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik:/etc/traefik
      - ./acme:/etc/certs

  traefik-certs-dumper:
    image: ghcr.io/kereis/traefik-certs-dumper:latest
    container_name: traefik-certs-dumper
    restart: unless-stopped
    depends_on:
      - traefik
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./acme:/traefik:ro
      - ./certs:/output

  posteio:
    image: analogic/poste.io
    restart: unless-stopped
    hostname: mail.$HOST
    volumes:
      - $JOHNCLOUD_ROOT/posteio:/data
    networks:
      default:
        ipv4_address: 172.19.0.5
    environment:
      TZ: $TZ
      HTTPS: OFF
      HTTP_PORT: 8534
      # HTTPS_PORT: 8535
      LETSENCRYPT_EMAIL: $ADMIN_EMAIL
      LETSENCRYPT_HOST: $ADMIN_EMAIL
      DISABLE_CLAMAV: $DISABLE_CLAMAV
      DISABLE_RSPAMD: $DISABLE_RSPAMD
      DISABLE_ROUNDCUBE: $DISABLE_ROUNDCUBE
    labels:
      - "traefik.enable=true"

      - traefik.http.routers.posteio.rule=Host(`mail.$HOST`) || Host(`autodiscover.$HOST`) || Host(`autoconfig.$HOST`) || Host(`mta-sts.$HOST`)
      - traefik.http.routers.posteio.entrypoints=https
      - traefik.http.routers.posteio.service=sposteio
      - traefik.http.services.sposteio.loadbalancer.server.port=8534

      - traefik.tcp.routers.smtp.rule=HostSNI(`*`)
      - traefik.tcp.routers.smtp.tls=false
      - traefik.tcp.routers.smtp.entrypoints=smtp
      - traefik.tcp.routers.smtp.service=smtp
      - traefik.tcp.services.smtp.loadbalancer.server.port=25
      - traefik.tcp.services.smtp.loadbalancer.proxyProtocol.version=2

      - traefik.tcp.routers.submission.rule=HostSNI(`*`)
      - traefik.tcp.routers.submission.tls.passthrough=true
      - traefik.tcp.routers.submission.entrypoints=submission
      - traefik.tcp.routers.submission.service=submission
      - traefik.tcp.services.submission.loadbalancer.server.port=587
      - traefik.tcp.services.submission.loadbalancer.proxyProtocol.version=2

      - traefik.tcp.routers.submissions.rule=HostSNI(`*`)
      - traefik.tcp.routers.submissions.tls.passthrough=true
      - traefik.tcp.routers.submissions.entrypoints=submissions
      - traefik.tcp.routers.submissions.service=submissions
      - traefik.tcp.services.submissions.loadbalancer.server.port=465
      - traefik.tcp.services.submissions.loadbalancer.proxyProtocol.version=2

      - traefik.tcp.routers.imaps.rule=HostSNI(`*`)
      - traefik.tcp.routers.imaps.tls.passthrough=true
      - traefik.tcp.routers.imaps.entrypoints=imaps
      - traefik.tcp.routers.imaps.service=imaps
      - traefik.tcp.services.imaps.loadbalancer.server.port=993
      - traefik.tcp.services.imaps.loadbalancer.proxyProtocol.version=2

networks:
  default:
    external: true
    name: traefik-proxy
    