services:
  # https://github.com/stalwartlabs/mail-server/discussions/206#discussioncomment-8438477
  traefik:
    image: traefik:latest
    restart: always
    networks:
      default:
        ipv4_address: 172.19.0.2
    ports:
      - 80:80
      - 443:443
      - 25:25
      - 465:465
      - 993:993
      - 587:587
    command:
      - --entrypoints.smtp.address=:25/tcp
      - --entrypoints.smtp.proxyProtocol.trustedIPs=172.19.0.0/24
      - --entrypoints.submissions.address=:465/tcp
      - --entrypoints.submissions.proxyProtocol.trustedIPs=172.19.0.0/24
      - --entrypoints.imaps.address=:993/tcp
      - --entrypoints.imaps.proxyProtocol.trustedIPs=172.19.0.0/24
      - --entrypoints.submission.address=:587/tcp
      - --entrypoints.submission.proxyProtocol.trustedIPs=172.19.0.0/24
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      # - --entrypoints.websecure.http.tls.certresolver=letsencrypt
      # - --entrypoints.websecure.http.tls.domains.main=$HOST
      # - --entrypoints.websecure.http.tls.domains.sans=*.$HOST
      # - --entrypoints.websecure.http.middlewares=default@file
      - --providers.docker=true
      - --providers.docker.exposedByDefault=false
      # - --providers.file.directory=/configuration
      # - --providers.file.watch=true
      - --api.dashboard=true
      - --api.insecure=true
      - --accesslog=true
      - --accesslog.filepath=/var/logs/access.log
      - --accesslog.fields.defaultMode=keep
      - --accesslog.fields.names.StartUTC=drop
      - --accesslog.format=json
      # - --experimental.plugins.wafrisPlugin.moduleName=github.com/Wafris/wafris-traefik
      # - --experimental.plugins.wafrisPlugin.version=v0.0.2
      - --certificatesresolvers.letsencrypt.acme.email=$ADMIN_EMAIL
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $JOHNCLOUD_ROOT/traefik/logs:/var/logs
      - $JOHNCLOUD_ROOT/traefik/letsencrypt:/letsencrypt
      # - $JOHNCLOUD_ROOT/traefik/etc:/configuration
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.$HOST`)
      - traefik.http.routers.traefik.service=api@internal
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls.certresolver=letsencrypt

  certsdumper:
    image: ghcr.io/kereis/traefik-certs-dumper:latest
    restart: unless-stopped
    depends_on:
      - traefik
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $JOHNCLOUD_ROOT/traefik/letsencrypt:/traefik:ro
      - $JOHNCLOUD_ROOT/traefik/certs:/output

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
    
