services:
  # https://github.com/stalwartlabs/mail-server/discussions/206#discussioncomment-8438477
  traefik:
    image: traefik:v3.0
    container_name: traefik
    restart: always
    networks:
      default:
        ipv4_address: 172.19.0.2
    ports:
      - 80:80
      - 443:443
      - 25:25
      - 465:465
      - 993:993
      - 587:587
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./traefik:/etc/traefik
      - ./acme:/etc/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro

  traefik-certs-dumper:
    image: ghcr.io/kereis/traefik-certs-dumper:latest
    container_name: traefik-certs-dumper
    restart: unless-stopped
    depends_on:
      - traefik
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./acme:/traefik:ro
      - ./certs:/output

  mailserver:
    # swaks --to yann@johncloud.fr --from yann@johntest.ovh --server mail.johntest.ovh --auth-user yann --protocol SSMTP --port 465 --auth-password It2rhHzn3xujowBNTn
    image: stalwartlabs/mail-server:latest
    container_name: mailserver
    restart: unless-stopped
    hostname: mail.$HOST
    depends_on:
      - traefik
    networks:
      default:
        ipv4_address: 172.19.0.5
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data:/opt/stalwart-mail
      - ./certs:/data/certs:ro
    labels:
      - traefik.enable=true

      - traefik.http.routers.mailserver.rule=Host(`mail.$HOST`) || Host(`autodiscover.$HOST`) || Host(`autoconfig.$HOST`) || Host(`mta-sts.$HOST`)
      - traefik.http.routers.mailserver.entrypoints=https
      - traefik.http.routers.mailserver.service=mailserver
      - traefik.http.services.mailserver.loadbalancer.server.port=8080

      - traefik.tcp.routers.smtp.rule=HostSNI(`*`)
      - traefik.tcp.routers.smtp.tls=false
      - traefik.tcp.routers.smtp.entrypoints=smtp
      - traefik.tcp.routers.smtp.service=smtp
      - traefik.tcp.services.smtp.loadbalancer.server.port=25
      - traefik.tcp.services.smtp.loadbalancer.proxyProtocol.version=2

      # - traefik.tcp.routers.jmap.rule=HostSNI(`*`)
      # - traefik.tcp.routers.jmap.tls.passthrough=true
      # - traefik.tcp.routers.jmap.entrypoints=https
      # - traefik.tcp.routers.jmap.service=jmap
      # - traefik.tcp.services.jmap.loadbalancer.server.port=443
      # - traefik.tcp.services.jmap.loadbalancer.proxyProtocol.version=2

      - traefik.tcp.routers.submission.rule=HostSNI(`*`)
      - traefik.tcp.routers.submission.tls.passthrough=true
      - traefik.tcp.routers.submission.entrypoints=submission
      - traefik.tcp.routers.submission.service=submission
      - traefik.tcp.services.submission.loadbalancer.server.port=587
      - traefik.tcp.services.submission.loadbalancer.proxyProtocol.version=2

      - traefik.tcp.routers.submissions.rule=HostSNI(`*`)
      - traefik.tcp.routers.submissions.tls.passthrough=true
      - traefik.tcp.routers.submissions.entrypoints=submissions
      - traefik.tcp.routers.submissions.service=submissions
      - traefik.tcp.services.submissions.loadbalancer.server.port=465
      - traefik.tcp.services.submissions.loadbalancer.proxyProtocol.version=2

      - traefik.tcp.routers.imaps.rule=HostSNI(`*`)
      - traefik.tcp.routers.imaps.tls.passthrough=true
      - traefik.tcp.routers.imaps.entrypoints=imaps
      - traefik.tcp.routers.imaps.service=imaps
      - traefik.tcp.services.imaps.loadbalancer.server.port=993
      - traefik.tcp.services.imaps.loadbalancer.proxyProtocol.version=2

networks:
  default:
    external: true
    name: $TRAEFIK_NETWORK
    