---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services
- Platform:
    - NextDNS:
        href: https://my.nextdns.io/c89b91
        icon: nextdns.png
        description: Le nouveau pare-feu pour l'Internet moderne.
    - Tailscale:
        href: https://login.tailscale.com/admin/machines
        icon: tailscale.png
        description: Zero config VPN service
    # - Dynatrace:
    #     icon: https://www.fluentd.org/images/datasources/dynatrace.png
    #     href: https://efm62819.live.dynatrace.com
    #     description: Resource dashboard
    # - Betterstack:
    #     href: https://status.johncloud.fr/
    #     # icon: https://uptime.betterstack.com/status-badges/v2/monitor/1fmxl.svg
    #     icon: https://logs.betterstack.com/assets/dashboards/better-stack-logo-mark-a0a7818e083fc04f3d3c933d56f8f4d66fb084aee850f066a4f23febee933bc5.svg
    #     description: Better Stack lets you see inside any stack, debug any issue, and resolve any incident.
    - Google Search:
        href: https://search.google.com/search-console?resource_id=sc-domain%3Ajohncloud.fr
        icon: google.png
        description: Contrôler et maintenir la présence de votre site dans les résultats de recherche Google
    - Google Postmaster:
        href: https://postmaster.google.com/v2/sender_compliance?domain=johncloud.fr
        icon: https://www.gstatic.com/postmaster/logo/logo-icon_512dp.svg
        description: Conformité aux exigences Google à l'intention des expéditeurs d'e-mails
        