# https://blog.filador.fr/je-supervise-mon-traefik-avec-prometheus-et-grafana/

version: '3'

services:
  prometheus:
    image: prom/prometheus:v2.15.2
    restart: unless-stopped
    container_name: prometheus
    user: "0:0"
    env_file: .env
    volumes:
      - ./prometheus/:/etc/prometheus/
      - $JOHNCLOUD_ROOT/monitoring/prometheus/db:/prometheus
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command:
      - "--web.route-prefix=/"
      - "--web.external-url=https://$PROM_HOST"
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prometheus-secure.entrypoints=websecure"
      - "traefik.http.routers.prometheus-secure.rule=Host(`$PROM_HOST`)"
      - "traefik.http.routers.prometheus-secure.middlewares=forward-auth-verify"
      - "traefik.http.routers.prometheus-secure.tls=true"
      - "traefik.http.routers.prometheus-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.prometheus-secure.service=prometheus"
      - "traefik.http.services.prometheus.loadbalancer.server.port=9090"

  grafana:
    image: grafana/grafana:6.6.1
    restart: unless-stopped
    container_name: grafana
    user: "0:0"
    env_file: .env
    volumes:
      - $JOHNCLOUD_ROOT/monitoring/grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - prometheus
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.grafana-secure.entrypoints=websecure"
      - "traefik.http.routers.grafana-secure.rule=Host(`$GF_HOST`)"
      - "traefik.http.routers.grafana-secure.middlewares=forward-auth-verify"
      - "traefik.http.routers.grafana-secure.tls=true"
      - "traefik.http.routers.grafana-secure.tls.certresolver=letsencrypt"
      - "traefik.http.routers.grafana-secure.service=grafana"
      - "traefik.http.services.grafana.loadbalancer.server.port=3000"

networks:
  default:
    external: true
    name: traefik-proxy
    
