# https://blog.filador.fr/je-supervise-mon-traefik-avec-prometheus-et-grafana/
# env $(cat .env | xargs) envsubst < ./docker-compose.yml | sudo docker stack deploy --compose-file - traefik

version: "3"

services:
  traefik:
    image: traefik:v2.10.4
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $JOHNCLOUD_ROOT/traefik/log:/var/log/traefik/
      - $JOHNCLOUD_ROOT/traefik/letsencrypt:/letsencrypt
    command:
      - --entrypoints.web.address=:80
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls.certResolver=letsencrypt
      - --providers.docker.swarmMode=true
      - --api.dashboard=true
      - --api.insecure=false
      - --certificatesResolvers.letsencrypt.acme.email=$ADMIN_EMAIL
      - --certificatesResolvers.letsencrypt.acme.storage=/letsencrypt/acme.json
      - --certificatesResolvers.letsencrypt.acme.httpChallenge.entrypoint=web
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.traefik.rule=Host(`$HOST`)"
        - "traefik.docker.network=traefik-proxy"
        - "traefik.http.routers.traefik.service=api@internal"
        - "traefik.http.routers.traefik.entrypoints=websecure"
        - "traefik.http.routers.traefik.tls.certresolver=letsencrypt"
        - "traefik.http.routers.traefik.middlewares=forward-auth-verify"
        - "traefik.http.services.traefik.loadbalancer.server.port=8080"

  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:latest
    environment:
      - TZ=$TZ
      - PROVIDERS_GOOGLE_CLIENT_ID=$PROVIDERS_GOOGLE_CLIENT_ID
      - PROVIDERS_GOOGLE_CLIENT_SECRET=$PROVIDERS_GOOGLE_CLIENT_SECRET
      - SECRET=$SECRET
      - AUTH_HOST=$AUTH_HOST
      - COOKIE_DOMAIN=$COOKIE_DOMAIN
      - WHITELIST=$WHITELIST
      - INSECURE_COOKIE=$INSECURE_COOKIE
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.forward.rule=Host(`$AUTH_HOST`)"   
        - "traefik.http.routers.forward.entrypoints=websecure"
        - "traefik.http.routers.forward.tls.certresolver=letsencrypt"
        - "traefik.http.services.forward.loadbalancer.server.port=4181"
        - "traefik.http.middlewares.forward-auth-verify.forwardauth.address=http://traefik-forward-auth:4181"      
        - "traefik.http.middlewares.forward-auth-verify.forwardauth.authResponseHeaders=X-Forwarded-User"

  whoami:
    image: traefik/whoami:latest
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoami.rule=Host(`whoami.douceville.fr`)"   
        - "traefik.http.routers.whoami.entrypoints=websecure"
        - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"
        - "traefik.http.services.whoami.loadbalancer.server.port=80"

  certdumper:
    image: ldez/traefik-certs-dumper:v2.8.1
    entrypoint: sh -c '
      apk add jq
      ; while ! [ -e /traefik/acme.json ]
      || ! [ `jq ".[] | .Certificates | length" /traefik/acme.json` != 0 ]; do
      sleep 1
      ; done
      && traefik-certs-dumper file --version v2 --watch
        --source /traefik/acme.json --dest /output
        --domain-subdir --crt-ext=.pem --key-ext=.pem'
    volumes:
      - $JOHNCLOUD_ROOT/traefik/letsencrypt:/traefik:ro
      - $JOHNCLOUD_ROOT/traefik/certs:/output
    deploy:
      labels:
        - "traefik.enable=false"

networks:
  default:
    external: true
    name: traefik-proxy
    
