# /routers/routers.yml

http:
  routers:
    dashboard:
      entrypoints: "api"
      service: "api@internal"
      middlewares: auth
      rule: "Host(`traefik.johncloud.fr`)"

  middlewares:
    auth:
      basicauth:
        users: "ydethe:$$apr1$$I7mMEVPl$$isHvciO04iOsTkywtBVrv."
