http:
  middlewares:
    default:
      chain:
        middlewares:
          - waf-plugin
    
    waf-plugin:
      plugin:
        wafrisPlugin:
          url: "redis://TpuxPNCe59JMcKhnWdKp4eH4vh2ZYZ9U3GXWywALMA@redis-dedicated-cdg-hyihu66pn90z.fly.dev:9987"
          wafris_timeout: 3

tls:
  options:
    default:
      sniStrict: true
      