entryPoints:
  web:
    address: ":80"
    http:
      # redirections:
      #   entryPoint:
      #     to: websecure
      #     scheme: https
      #     permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

providers:
  docker: {}
    # endpoint: "unix:///var/run/docker.sock"
    # watch: true
    # exposedByDefault: false
  file:
    filename: "/routers/routers.yml"
    watch: true

api:
  dashboard: true
  # insecure: true

certificatesResolvers:
  letsencrypt:
    acme:
      email: "ydethe@gmail.com"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web
