entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true

  websecure:
    address: ":443"
    http:
      tls:
        certResolver: letsencrypt

  metrics:
    address: ":8082"

providers:
  docker: {}
    # endpoint: "unix:///var/run/docker.sock"
    # watch: true
    # exposedByDefault: false
  file:
    directory: "/routers" # Adjust the path according your needs.
    watch: true

api:
  dashboard: true
  insecure: false

certificatesResolvers:
  letsencrypt:
    acme:
      email: "ydethe@gmail.com"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web

accessLog:
  filePath: "/var/log/traefik/access.log"
  format: json

metrics:
  prometheus:
    # Nom du point d'entrée défini au dessus
    entryPoint: metrics
    # On configure la latence des métriques
    buckets:
      - 0.1
      - 0.3
      - 1.2
      - 5.0
    # Ajout des métriques sur les points d'entrée
    addEntryPointsLabels: true
    # Ajout des services
    addServicesLabels: true
