# https://sparwan.com/articles/post/creer-votre-serveur-cloud-tuto-d-installation-de-nextcloud-via-docker-compose.html
version: '3.8'

services:
  nextcloud_db:
    image: mariadb
    container_name: nextcloud_db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - $JOHNCLOUD_ROOT/nextcloud/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$NEXTCLOUD_MYSQL_ROOT_PASSWORD # Mot de passe de l'utilisateur root de mariadb
      - MYSQL_DATABASE=$NEXTCLOUD_MYSQL_DATABASE # Nom de la base de données à créer à l'initialisation du conteneur
      - MYSQL_USER=$NEXTCLOUD_MYSQL_USER # Nom de l'utilisateur de la base de données créée
      - MYSQL_PASSWORD=$NEXTCLOUD_MYSQL_PASSWORD # Mot de passe de l'utilisateur créé
    labels:
      - "traefik.enable=false"

  nextcloud_app:
    image: nextcloud
    restart: unless-stopped
    ports:
      - $NEXTCLOUD_PORT:80
    volumes:
      - $JOHNCLOUD_ROOT/nextcloud/data:/var/www/html
    environment:
      - MYSQL_HOST=nextcloud_db # Nom du conteneur de la base de données
      - MYSQL_DATABASE=$NEXTCLOUD_MYSQL_DATABASE # Nom de la base de données
      - MYSQL_USER=$NEXTCLOUD_MYSQL_USER # Nom de l'utilisateur de la base de données
      - MYSQL_PASSWORD=$NEXTCLOUD_MYSQL_PASSWORD # Mot de passe de l'utilisateur de la base de données
    depends_on:
      - nextcloud_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cloud.rule=Host(`$HOST`)"
      - "traefik.http.routers.cloud.entrypoints=websecure"
      - "traefik.http.routers.cloud.tls.certresolver=letsencrypt"

networks:
  default:
    external: true
    name: traefik-proxy
    
