version: '3.1'

services:
  wordpress:
    image: wordpress
    restart: unless-stopped
    ports:
      - 8082:80
    environment:
      WORDPRESS_DB_HOST: $DB_HOST
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD
      WORDPRESS_DB_NAME: $DB_NAME
    volumes:
      - $JOHNCLOUD_ROOT/wordpress/data:/var/www/html
    depends_on:
      - wordpress_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`$HOST`)"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=letsencrypt"

  wordpress_db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: $DB_NAME
      MYSQL_USER: $DB_USER
      MYSQL_PASSWORD: $DB_PASSWORD
      MYSQL_RANDOM_ROOT_PASSWORD: $DB_RANDOM_ROOT_PASSWORD
    volumes:
      - $JOHNCLOUD_ROOT/wordpress/db:/var/lib/mysql
    labels:
      - "traefik.enable=false"

networks:
  default:
    external: true
    name: traefik-proxy
    