version: '3.1'

services:

  wordpress:
    image: wordpress
    restart: unless-stopped
    ports:
      - 8082:80
    environment:
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: exampleuser
      WORDPRESS_DB_PASSWORD: MhbT6W3BGYk62tz6gX7V
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - ./wordpress:/var/www/html
    depends_on:
      - wordpress_db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress.rule=Host(`wordpress.johncloud.fr`)"
      - "traefik.http.routers.wordpress.entrypoints=websecure"
      - "traefik.http.routers.wordpress.tls.certresolver=letsencrypt"

  wordpress_db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: MhbT6W3BGYk62tz6gX7V
      MYSQL_RANDOM_ROOT_PASSWORD: 'ZjqRTVqKHU55yGKaDj9n'
    volumes:
      - ./db:/var/lib/mysql

networks:
  default:
    external: true
    name: traefik-proxy
    