{
 "title": "Grafana mdadm overview dashboard",
 "description": "Prometheus node_exporter mdadm module dashboard. Per Server and per md view",
 "tags": [
  "node",
  "disk",
  "mdstat"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_md_disks, instance)"
    }
   },
   {
    "name": "host",
    "query": {
     "query": "label_values(node_md_disks{instance=~\"$instance\"}, instance)"
    }
   },
   {
    "name": "md",
    "query": {
     "query": "label_values(node_md_state{instance=~\"$instance\"}, device)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Dashboard Row",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "All mds are active",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_md_state{instance=~\"$instance\",state=\"active\"}) / count(node_md_state{instance=~\"$instance\",state=\"active\"})"
    }
   ]
  },
  {
   "title": "All md disks are active",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_md_disks{state=\"active\",instance=~\"$instance\"}) / sum(node_md_disks{state=\"active\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total Active Disks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_md_disks{state=\"active\",instance=~\"$instance\"}) / count(node_md_disks{state=\"active\", instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Total installed Disks",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_md_disks{instance=~\"$instance\"})/count(node_md_disks{instance=~\"$instance\",state=\"active\"})"
    }
   ]
  },
  {
   "title": "Total MD RAIDs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_md_disks{instance=~\"$instance\",state=\"active\"})"
    }
   ]
  },
  {
   "title": "$md RAID",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "repeat": "md",
   "targets": [
    {}
   ]
  },
  {
   "title": "$md status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disks status in $md",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_md_disks{instance=~\"$instance\",device=\"$md\"}) /  sum(node_md_disks_required{instance=~\"$instance\",device=\"$md\"})"
    }
   ]
  },
  {
   "title": "Disks active in RAID $instance $md",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "node_md_disks{instance=~\"$instance\",device=\"$md\",state=\"active\"}"
    }
   ]
  },
  {
   "title": "Disks configured in RAID $host $md",
   "type": "stat",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(node_md_disks{instance=~\"$instance\",device=\"$md\"})"
    }
   ]
  },
  {
   "title": "Sync ratio $instance $md",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(node_md_blocks_synced{instance=~\"$instance\",device=\"$md\"} / node_md_blocks{instance=~\"$instance\",device=\"$md\"}) * 100",
     "legendFormat": "{{device }}"
    }
   ]
  }
 ]
}