version: '3.1'

services:
  app:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - 8761:8000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - $JOHNCLOUD_ROOT/portainer/data:/data
    networks:
      - internal
      -  traefik-proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`$HOST`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.http.services.portainer.loadbalancer.server.port=8000"
      - "traefik.http.routers.portainer.middlewares=forward-auth-verify"

  agent:
    image: portainer/agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - internal

networks:
  default:
    external: true
    name: traefik-proxy
  internal:
    driver: overlay
    ipam:
      config:
        - subnet: 172.16.13.0/24
    
