version: '3.1'

services:
  app:
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    ports:
      - 8761:8000
    environment:
      TZ: $TZ
      WORDPRESS_DB_HOST: wordpress_db
      WORDPRESS_DB_USER: $DB_USER
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD
      WORDPRESS_DB_NAME: $DB_NAME
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $JOHNCLOUD_ROOT/portainer/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(`$HOST`)"
      - "traefik.http.routers.portainer.entrypoints=websecure"
      - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
      - "traefik.http.services.portainer.loadbalancer.server.port=8000"
      - "traefik.http.routers.portainer.middlewares=forward-auth-verify"

networks:
  default:
    external: true
    name: traefik-proxy
    
