# env $(cat .env | xargs) envsubst < ./docker-compose.yml | sudo docker stack deploy --compose-file - portainer

version: '3.1'

services:
  app:
    image: portainer/portainer-ce:latest
    ports:
      - 9761:9000
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - $JOHNCLOUD_ROOT/portainer/data:/data
    networks:
      - traefik-proxy
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.portainer.rule=Host(`$HOST`)"
        - "traefik.docker.network=traefik-proxy"
        - "traefik.http.routers.portainer.entrypoints=websecure"
        - "traefik.http.routers.portainer.tls.certresolver=letsencrypt"
        - "traefik.http.services.portainer.loadbalancer.server.port=9000"

networks:
  traefik-proxy:
    external: true
    # name: traefik-proxy
    