---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Bureautique:
    - Feedly:
        href: https://feedly.com/i
        icon: feedly.svg
        description: News Reader
        
    - Raindrop:
        href: https://app.raindrop.io/my/0
        icon: https://cdn.jim-nielsen.com/ios/1024/raindrop-io-2025-12-08.png
        description: All-in-one bookmark manager
