version: '3.1'

services:
  # External dependencies
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - $JOHNCLOUD_ROOT/mailu/redis:/data
    depends_on:
      - resolver
    dns:
      - 192.168.203.254
    labels:
      - "traefik.enable=false"

  certdumper:
    restart: unless-stopped
    image: ldez/traefik-certs-dumper:latest
    entrypoint: sh -c '
      apk add jq
      ; while ! [ -e /traefik/acme.json ]
      || ! [ `jq ".[] | .Certificates | length" /traefik/acme.json` != 0 ]; do
      sleep 1
      ; done
      && traefik-certs-dumper file --version v2 --watch
        --source /traefik/acme.json --dest /output
        --domain-subdir --crt-ext=.pem --key-ext=.pem'
    volumes:
      - $JOHNCLOUD_ROOT/traefik/letsencrypt:/traefik:ro
      - $JOHNCLOUD_ROOT/traefik/certs:/output
    labels:
      - "traefik.enable=false"

  # Core services
  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2.0}
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: mailu-front
    ports:
      - "188.165.234.144:25:25"
      - "188.165.234.144:465:465"
      - "188.165.234.144:587:587"
      - "188.165.234.144:110:110"
      - "188.165.234.144:995:995"
      - "188.165.234.144:143:143"
      - "188.165.234.144:993:993"
    networks:
      - default
      - webmail
      - radicale
    volumes:
      - $JOHNCLOUD_ROOT/mailu/overrides/nginx:/overrides:ro
      - $JOHNCLOUD_ROOT/traefik/certs/mail.johncloud.fr/certificate.pem:/certs/cert.pem
      - $JOHNCLOUD_ROOT/traefik/certs/mail.johncloud.fr/privatekey.pem:/certs/key.pem
    depends_on:
      - resolver
    dns:
      - 192.168.203.254
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`mail.johncloud.fr`)"
      - "traefik.http.services.front.loadbalancer.server.port=80"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls=true"
      - "traefik.http.routers.front.tls.certresolver=letsencrypt"
      - "traefik.http.routers.front_admin.rule=Host(`mail.johncloud.fr`) && PathPrefix(`/admin`)"
      - "traefik.http.routers.front_admin.entrypoints=websecure"
      - "traefik.http.routers.front_admin.tls=true"
      - "traefik.http.routers.front_admin.tls.certresolver=letsencrypt"

  resolver:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}unbound:${MAILU_VERSION:-2.0}
    restart: unless-stopped
    networks:
      default:
        ipv4_address: 192.168.203.254
    labels:
      - "traefik.enable=false"

  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2.0}
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - $JOHNCLOUD_ROOT/mailu/data:/data
      - $JOHNCLOUD_ROOT/mailu/dkim:/dkim
    depends_on:
      - redis
      - resolver
    dns:
      - 192.168.203.254
    labels:
      - "traefik.enable=false"

  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2.0}
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - $JOHNCLOUD_ROOT/mailu/mail:/mail
      - $JOHNCLOUD_ROOT/mailu/overrides/dovecot:/overrides:ro
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254
    labels:
      - "traefik.enable=false"

  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2.0}
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - $JOHNCLOUD_ROOT/mailu/mailqueue:/queue
      - $JOHNCLOUD_ROOT/mailu/overrides/postfix:/overrides:ro
    depends_on:
      - front
      - resolver
    dns:
      - 192.168.203.254
    labels:
      - "traefik.enable=false"

  oletools:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-2.0}
    hostname: oletools
    restart: unless-stopped
    networks:
      - noinet
    depends_on:
      - resolver
    dns:
      - 192.168.203.254
    labels:
      - "traefik.enable=false"

  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2.0}
    hostname: antispam
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    networks:
      - default
      - noinet
    volumes:
      - $JOHNCLOUD_ROOT/mailu/filter:/var/lib/rspamd
      - $JOHNCLOUD_ROOT/mailu/overrides/rspamd:/overrides:ro
    depends_on:
      - front
      - redis
      - oletools
      - antivirus
      - resolver
    dns:
      - 192.168.203.254
    labels:
      - "traefik.enable=false"

  # Optional services
  antivirus:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-2.0}
    restart: unless-stopped
    volumes:
      - $JOHNCLOUD_ROOT/mailu/filter:/data
    depends_on:
      - resolver
    dns:
      - 192.168.203.254
    labels:
      - "traefik.enable=false"

  webdav:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-2.0}
    restart: unless-stopped
    volumes:
      - $JOHNCLOUD_ROOT/mailu/dav:/data
    networks:
      - radicale
    labels:
      - "traefik.enable=false"

  fetchmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-2.0}
    restart: unless-stopped
    volumes:
      - $JOHNCLOUD_ROOT/mailu/data/fetchmail:/data
    depends_on:
      - admin
      - smtp
      - imap
      - resolver
    dns:
      - 192.168.203.254
    labels:
      - "traefik.enable=false"

  # Webmail
  webmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2.0}
    restart: unless-stopped
    volumes:
      - $JOHNCLOUD_ROOT/mailu/webmail:/data
      - $JOHNCLOUD_ROOT/mailu/overrides/roundcube:/overrides:ro
    networks:
      - webmail
    depends_on:
      - front
    labels:
      - "traefik.enable=false"

networks:
  default:
    external: true
    name: traefik-proxy
  radicale:
    driver: bridge
  webmail:
    driver: bridge
  noinet:
    driver: bridge
    internal: true
