version: '3.1'

services:
  # External dependencies
  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - $JOHNCLOUD_ROOT/mailu/redis:/data
    labels:
      - "traefik.enable=false"

  # Core services
  front:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2.0}
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: mailu-front
    networks:
      - default
      - traefik-public
    ports:
      - "$REAL_IP_FROM:25:25"
      - "$REAL_IP_FROM:465:465"
      - "$REAL_IP_FROM:587:587"
      - "$REAL_IP_FROM:110:110"
      - "$REAL_IP_FROM:995:995"
      - "$REAL_IP_FROM:143:143"
      - "$REAL_IP_FROM:993:993"
    volumes:
      - $JOHNCLOUD_ROOT/mailu/overrides/nginx:/overrides:ro
      - $JOHNCLOUD_ROOT/traefik/certs/$TRAEFIK_DOMAIN/certificate.pem:/certs/cert.pem
      - $JOHNCLOUD_ROOT/traefik/certs/$TRAEFIK_DOMAIN/privatekey.pem:/certs/key.pem
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=Host(`$TRAEFIK_DOMAIN`)"
      - "traefik.http.routers.front.entrypoints=websecure"
      - "traefik.http.routers.front.tls=true"
      - "traefik.http.routers.front.tls.certresolver=letsencrypt"
      - "traefik.http.routers.front.service=mailu-websecure-svc"
      - "traefik.http.services.mailu-websecure-svc.loadbalancer.server.port=80"

  admin:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2.0}
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: mailu-admin
    volumes:
      - $JOHNCLOUD_ROOT/mailu/data:/data
      - $JOHNCLOUD_ROOT/mailu/dkim:/dkim
    depends_on:
      - redis
    labels:
      - "traefik.enable=false"

  imap:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2.0}
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: mailu-imap
    volumes:
      - $JOHNCLOUD_ROOT/mailu/mail:/mail
      - $JOHNCLOUD_ROOT/mailu/overrides/dovecot:/overrides:ro
    depends_on:
      - front
    labels:
      - "traefik.enable=false"

  smtp:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2.0}
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: mailu-smtp
    volumes:
      - $JOHNCLOUD_ROOT/mailu/mailqueue:/queue
      - $JOHNCLOUD_ROOT/mailu/overrides/postfix:/overrides:ro
    depends_on:
      - front
    labels:
      - "traefik.enable=false"

  oletools:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}oletools:${MAILU_VERSION:-2.0}
    hostname: oletools
    restart: unless-stopped
    labels:
      - "traefik.enable=false"

  antispam:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}rspamd:${MAILU_VERSION:-2.0}
    hostname: antispam
    restart: unless-stopped
    logging:
      driver: journald
      options:
        tag: mailu-antispam
    volumes:
      - $JOHNCLOUD_ROOT/mailu/filter:/var/lib/rspamd
      - $JOHNCLOUD_ROOT/mailu/overrides/rspamd:/overrides:ro
    depends_on:
      - front
      - redis
      - oletools
      - antivirus
    labels:
      - "traefik.enable=false"

  # Optional services
  antivirus:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}clamav:${MAILU_VERSION:-2.0}
    restart: unless-stopped
    volumes:
      - $JOHNCLOUD_ROOT/mailu/filter:/data
    labels:
      - "traefik.enable=false"

  webdav:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}radicale:${MAILU_VERSION:-2.0}
    restart: unless-stopped
    volumes:
      - $JOHNCLOUD_ROOT/mailu/dav:/data
    labels:
      - "traefik.enable=false"

  fetchmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}fetchmail:${MAILU_VERSION:-2.0}
    restart: unless-stopped
    volumes:
      - $JOHNCLOUD_ROOT/mailu/data/fetchmail:/data
    depends_on:
      - admin
      - smtp
      - imap
    labels:
      - "traefik.enable=false"

  # Webmail
  webmail:
    image: ${DOCKER_ORG:-ghcr.io/mailu}/${DOCKER_PREFIX:-}webmail:${MAILU_VERSION:-2.0}
    restart: unless-stopped
    volumes:
      - $JOHNCLOUD_ROOT/mailu/webmail:/data
      - $JOHNCLOUD_ROOT/mailu/overrides/roundcube:/overrides:ro
    depends_on:
      - front
    labels:
      - "traefik.enable=false"

networks:
  traefik-public:
    external: true
    name: traefik-proxy
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: $SUBNET
